# Generated by Django 4.1.5 on 2023-02-15 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_tag',
            field=models.CharField(default='Page tab title', help_text='The title contains 23 characters, no more', max_length=23),
        ),
    ]
