# Generated by Django 4.1.5 on 2023-02-22 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0006_profile_facebook_url_profile_instagram_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='facebook_url',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='instagram_url',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='pinterest_url',
        ),
    ]
