# Generated by Django 4.1.5 on 2023-02-27 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0009_alter_profile_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
    ]
